### ISSUE TITLE
Standing QA relay

### ISSUE THREAD

**Issue by mirestrepo** [brown-bnc/roadmap#10]
Full completion of a second xnat relay instance

**Comment by fordmcdonald** [comment]
The top level goals of this issues are to:
- Provide backup XNAT-Relay for the MRF 
- Provide QA Instance for Load / System Testing
- Refactor Installation of XNAT and Tomcat to Run in Containers 

Tasks:
- [x] https://github.com/brown-bnc/xnat-relay/issues/38
